[build]
target = "armv7-linux-androideabi"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi23-clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-linux-android]
linker = "aarch64-linux-android23-clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.i686-linux-android]
linker = "i686-linux-android23-clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-linux-android]
linker = "x86_64-linux-android23-clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
